/**:
  ros__parameters:
    # Topics
    camera_topic: "/camera/image_raw"
    camera_info: "/camera/camera_info"
    lidar_topic: "/ouster/points"

    # Point cloud filtering bounds (adjustable via parameters)
    bounds:
      x_min: -20.0
      x_max: -3.0
      y_min: -4.0
      y_max: 4.0
      z_min: -1.7
      z_max: 0.0
      k: 50
      z: 1.0
      voxel_res: 0.4

    # Properties of chessboard calibration target (nested structure)
    chessboard:
      pattern_size:
        width: 5
        height: 7
      square_length: 70
      board_dimension:
        width: 620
        height: 480
      translation_error:
        x: 2
        y: 2
